CREATE TABLE IF NOT EXISTS recipe_details (
    id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipe_id       INTEGER NOT NULL,
    
    -- Relaciones opcionales (Solo una debe estar llena por fila)
    ingredient_id   INTEGER NULL,
    product_id      INTEGER NULL,
    
    quantity        NUMERIC(10, 2) NOT NULL,
    unit            VARCHAR(20) NOT NULL, -- Ej: 'gr', 'ml', 'und'
    
    -- Auditoría
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Constraints de Integridad
    CONSTRAINT fk_recipe_details_recipes 
        FOREIGN KEY (recipe_id) REFERENCES recipes (id) ON DELETE CASCADE,
        
    CONSTRAINT fk_recipe_details_ingredients 
        FOREIGN KEY (ingredient_id) REFERENCES ingredients (id) ON DELETE SET NULL,
        
    CONSTRAINT fk_recipe_details_products 
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE SET NULL,

    -- Validación: Una fila debe ser o ingrediente o producto, no ambos ni ninguno vacío
    CONSTRAINT ck_recipe_detail_type 
        CHECK (
            (ingredient_id IS NOT NULL AND product_id IS NULL) OR 
            (ingredient_id IS NULL AND product_id IS NOT NULL)
        )
);

-- Índices para optimizar las consultas de la receta
CREATE INDEX IX_recipe_details_recipe_id ON recipe_details (recipe_id);
CREATE INDEX IX_recipe_details_ingredient_id ON recipe_details (ingredient_id);
CREATE INDEX IX_recipe_details_product_id ON recipe_details (product_id);